### asyncの関数の戻り値はPromise


```javascript
const async = async () => 'foo'

console.log(async())

async().then(value => console.log(value))
```


```
> Promise {<resolved>: "foo"}
> foo
```


```javascript
const async = async () => {
  throw new Error('error occurred!')
}

async().catch(error => console.log(error.message))
```


```
> error occurred!
```


```javascript
const async1 = async () => {
  return '1'
}

const async2 = async () => {
  return '2'
}

const async3 = async () => {
  return '3'
}
```


```javascript
async1().then(value => {
  console.log(value)
  return async2()
}).then(value => {
  console.log(value)
  return async3()
}).then(value => {
  console.log(value)
})
```

```
> 1
> 2
> 3
```